# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app_pokedex_%kernel.environment%:
            index_name: app_pokedex
            client: default
            types:
                pokemon:
                    properties:
                        id: ~
                        number: ~
                        name:
                            boost: 100
                        description:
                            boost: 60
                        category:
                            type: "object"
                            properties:
                                id: ~
                                name:
                                    boost: 80
                        type:
                            type: "object"
                            properties:
                                id: ~
                                name:
                                    boost: 80
                                description:
                                    boost: 40
                    persistence:
                        driver: orm
                        model: App\Entity\Pokemon
                        provider: ~
                        finder: ~
